return {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      ltex = {
        filetypes = { "html" },
        settings = {
          ltex = {
            language = "pt-BR",
            dictionary = {
              ["pt-BR"] = {
                -- Boilerplate e Snippet HTML5 (!)
                "doctype",
                "html",
                "lang",
                "charset",
                "utf-8",
                "viewport",
                "content",
                "width",
                "device-width",
                "initial-scale",
                "http-equiv",
                "X-UA-Compatible",
                "edge",
                "title",
                "link",
                "rel",
                "stylesheet",
                "href",
                "script",
                "src",
                "body",
                "meta",
                "name",
                "async",
                "defer",

                -- Tags de Estrutura e Semântica
                "header",
                "nav",
                "main",
                "footer",
                "section",
                "article",
                "aside",
                "details",
                "summary",
                "figure",
                "figcaption",
                "div",
                "span",

                -- Tags de Texto e Listas
                "h1",
                "h2",
                "h3",
                "h4",
                "h5",
                "h6",
                "p",
                "br",
                "hr",
                "strong",
                "em",
                "blockquote",
                "pre",
                "code",
                "ul",
                "ol",
                "li",
                "dl",
                "dt",
                "dd",
                "mark",
                "small",
                "del",
                "ins",
                "sub",
                "sup",
                "b",
                "i",
                "u",

                -- Atributos Comuns (para o ltex não reclamar dentro das aspas)
                "id",
                "class",
                "style",
                "alt",
                "target",
                "title",
                "value",
                "placeholder",
                "type",
                "name",
                "required",
                "disabled",
                "checked",
                "selected",
                "hidden",
                "tabindex",
                "loading",
                "lazy",
                "itemprop",

                -- Formulários e Tabelas
                "form",
                "label",
                "input",
                "textarea",
                "button",
                "select",
                "option",
                "optgroup",
                "fieldset",
                "legend",
                "datalist",
                "table",
                "thead",
                "tbody",
                "tfoot",
                "tr",
                "th",
                "td",
                "caption",

                -- Multimídia e Embeds
                "img",
                "svg",
                "video",
                "audio",
                "source",
                "canvas",
                "iframe",
                "path",
                "rect",
                "circle",
                "viewBox",
                "fill",
                "xmlns",

                -- Termos Técnicos Extras (Comuns em Notetaking)
                "frontend",
                "backend",
                "api",
                "json",
                "git",
                "commit",
                "deploy",
                "setup",
                "config",
                "framework",
                "library",
                "markdown",
                "css",
                "js",
              },
            },
            -- Desativa o aviso de palavras com letras maiúsculas/minúsculas grudadas em atributos
            disabledRules = {
              ["pt-BR"] = { "UPPERCASE_SENTENCE_START", "MORFOLOGIK_RULE_PT_BR" },
            },
          },
        },
      },
    },
  },
}
